# Generated by Django 5.0.1 on 2024-06-05 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0043_remove_payment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='aadhar_card',
        ),
    ]
